### ISSUE TITLE
change get_ip_location endpoints to allow for logged in users

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#100]
Once we have logged in users we can change the way that the maps display the prayer warriors.

Rather than displaying unique hashes, which results in multiple symbols potentially for the same user (hashes are dependent on device/browser/ip etc)

If a record has a user id attached to it, we can use that user's location instead.

This may or may not need a change to the way that the `get_ip_location` endpoint works.
I don't see it needing changing, except for maybe the lap.js not calling the endpoint if the user is logged in and has a location set.

If we allow the user to opt out of location tracking, then if the user has no location, then the prayer report will also have no hash assosciated with it either

**Comment by ChrisChasm** [comment]
If I restated our strategy, it would probably be something like this.

(Tolerable) Anonymous users have their course location via ip address translated by IP stack, hash created, but cookies are blocked and their hash is recreated every visit.
(Good) Anonymous users have their course location via ip address translated by IPstack and a hash is assigned to their browser with a Cookie. So each visit is reconnected to the hash, even thought their location changes.
(Better) All signed in users have their course location and their hash from previous prayer added to their profile,  and all prayer logging uses this profile location source.
(Best) Signed in user defines their own prayer location through the user profile and all prayers are consistently logged with stable user location data.

I don't know if we will support a completely non location user prayer. We might consider allowing them to select "Alias my location". This will reduce the complexity of the mapping representation of "Opt out" prayer warriors. Honestly, the map isn't striving to show perfect location as much as participation. Right now, if you VPN or travel, we are picking up location variations. I think this needs reduced, but I don't think perfect user location representation is the goal. But showing participation is a priority.

**Comment by squigglybob** [comment]
Thanks for the clarification Chris 🙂

So that would mean that the (Good) version wouldn't change hash if they change location, only if they changed browser/device

**Comment by squigglybob** [comment]
I'm with you on all of those different levels.

I think they are all going to work just as they are currently programmed, the only difference being that the `get_ip_location` will return the user's saved location if they are logged in, rather than the ipstack location.
