### ISSUE TITLE
Add a hold screen to a custom lap with a future

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#102]
Currently when a lap has a future date, the lap is still open to pray. 

Fix: When a future date is set, supply a hold screen.

**Comment by squigglybob** [comment]
A leader is more likely to want to have the start time counting down to when it's open.

But... you do want the ability for people to jump on and be able to get a feel for things.

<<<
Here's the Northside Lap
It starts in 25 days
{{count down}}

They can click to pray some warm up prayers

-----------------------------------
Deep linking would be good to have in place before this is done

**Comment by squigglybob** [comment]
https://www.figma.com/file/60j2ZoU3nLXjy7CotB4fAn/P.G.?node-id=0%3A1&t=XOEJJUZTo89mzwIC-0

**Comment by squigglybob** [comment]
I'm guessing we would also want to have a similar overlay or something on the display map as well for displaying on the main screen
