### ISSUE TITLE
Change the prayer icon

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#103]
Issue: the current prayer warrior icon has negative feedback. It is also not scaling up and down with the zoom to better sizes. Overlapping is consistent because the quantity of prayer warriors is often 1000+.

Nominations for replacement icons

**Comment by ChrisChasm** [comment]
<img width="1668" alt="Screenshot 2022-12-19 at 9 55 42 AM" src="https://user-images.githubusercontent.com/7318348/208478729-7cf6e34a-00cb-4b80-b30f-d2fa05638e44.png">

**Comment by squigglybob** [comment]
Let's also try clustering the points as part of this

**Comment by squigglybob** [comment]
try adding a custom avatar to the clusters

**Comment by squigglybob** [comment]
Attempting a group of 4 images as a cluster image
![image](https://user-images.githubusercontent.com/9816214/209112134-eb0dce57-bbee-4217-b84f-6314330142a0.png)

🤢 I don't like it, and it get's very confusing as you zoom in and unclustered larger faces are there too eg
![image](https://user-images.githubusercontent.com/9816214/209112360-49550d2f-3056-40db-9423-7df5b59f17bc.png)

**Comment by squigglybob** [comment]
with a coloured circle with a few peoeple in it for the clusters
![image](https://user-images.githubusercontent.com/9816214/209118773-5882067e-73b7-494a-9919-6f0e5da98dd8.png)

and zoomed in with a mixture of clusters and non clusters
![image](https://user-images.githubusercontent.com/9816214/209118909-6caafce7-b236-4fd0-9818-e6bd3efdfbdf.png)

**Comment by squigglybob** [comment]
@ChrisChasm Do we want to have numbers on the clusters that represent how many people are in the cluster?

**Comment by squigglybob** [comment]
@ahillbilly @ChrisChasm 
we are going to swap the old black praying person with these new diverse icons to get improved icons. That's something that we definitely wanted.

We're not sure the best route for clustering, so we can address that in another iteration on another issue.

So i'll push the change with just the icon change and no clustering for now
