### ISSUE TITLE
User Profile: Deleting a user

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#106]
@ChrisChasm 

What level do we need to go to with this?

## Options of things to delete

1. user account
2. user and contact
3. user and contact and any links to groups/prayers made (location data is stored in prayers)

## Obfuscate and allow user to come back later

Or we could delete any POI from all of the above and keep a holding user or something with a hash of their email address

Then if the user re-registers with the hashed email address they would be able to recover their account to some extent, at least to retrieve made prayers etc.

What are your thoughts on this?

**Comment by ChrisChasm** [comment]
GDPR : Get my data, delete my data

Get Data Email Report
- [ ]  User name
- [ ] email address
- [ ] user provided address
- [ ] User linked to prayers ??? (Not sure)

Delete user account
- [ ] Delete user record
- [ ] Delete user_id from prayers, but do not delete the prayers

**Comment by squigglybob** [comment]
@ChrisChasm What should happen to groups that they were managing?

**Comment by squigglybob** [comment]
@ChrisChasm There are lots of places that the username of the deleted user could be copied to in text.

@ mentions in comment
username in activity log etc.

Do I need to go through and clean these all up?

Also what about the post author ids in the wp_posts table?
When a user is deleted in the WP admin (and also with the wp_delete_user function) you have to choose another user to change over the posts to as the author, otherwise all of the posts that they authored get deleted.

This would mean that we need to transfer over feedback and laps to another user so as to preserve those laps and feedbacks on the system.

Should we have a user called @deleted to re-assign posts to? or something like that?

**Comment by squigglybob** [comment]
hey @ChrisChasm I'd like to push back a little on the gdpr report thing.

I'm not sure what information would be in that report other than what they have already given and can easily see under their profile section where they click this button.

So, not really sure if we need it or not.
I guess if there was other info on them that we were going to collect, like connections to other people or things like that, that might be needed in the report.
