### ISSUE TITLE
Build an SEO landing pages

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#122]
Kudos to Dario!

Google Adwords can take a csv list of urls and get long tail prayer campaign. If we create urls that have a landing page for a location, a city, or a people groups?? We could build ad campaigns for Pray for Colorado, Pray for Denver, etc.

- [ ]  Establish URL structure plan
- [x] Build list of elements needed for the import to Adwords and a sample template csv
- [ ] Build the magic link
- [ ] Build the custom global prayer load strategy.

**Comment by prykon** [comment]
We would need a CSV file export with the following columns:
city name, state or province name, country name, landing url

This way we can create a long tail strategy for targeting keywords like "Pray for Boulder, Colorado". These keywords don't have a lot of competition and their CPC is low, but if someone actually searches for the term, our ad would be super relevant and user stickiness would be high.

These pages should have an H1 tag that says "Pray for {location_name}"
The page title tag sould be "Pray for {location_name} | Prayer.Global"
The page should have a link rel="canonical" tag that points to itself
All page content should be rendered server-side so Google can see it properly.

If we do all these things, we'll also get rebound traffic so it won't just bring paid traffic from Google Ads but also free organic traffic.

**Comment by prykon** [comment]
A nice-to-have would be a url parameter like `?first_visite=true` that, if present, would change the default firework celebration screen for a screen that reads something like: "By praying just now, you participated in a world-wide prayer effort for every corner of the world. Why don't you stay a while and pray for some other places?"

**Comment by squigglybob** [comment]
The url to get the pray for 1 specific location looks like

`https://prayer.global/prayer_app/global/cc8b6b/location?grid_id=100000015`

You can try it to see what happens, and I think it should be fairly easy to slip in another query param and add some wording on the celebration page as an explanation of what they have just been part of...

**Comment by prykon** [comment]
Thanks, @squigglybob !
What would the `cc8b6b` subdirectory be? Is it a prayer lap id? Will this id change on the next prayer lap?

**Comment by squigglybob** [comment]
Yes it's the prayer lap id. This currently only works for the global lap. we would need to check with @ChrisChasm if he made it so that the global lap preserves it's id, as that was a thought a while back and may well have been implemented

**Comment by prykon** [comment]
Is it possible to create a redirect rule where the prayer lap id get added dynamically if it doesn't exist? This way I can create Google Ads to the "id-less" url and then the system automatically redirects them to the proper page.

**For example:**
I create the ad pointing to this url:
`https://prayer.global/prayer_app/global/location?grid_id=100000015`

The system automatically redirects to:
`https://prayer.global/prayer_app/global/cc8b6b/location?grid_id=100000015`

**Comment by squigglybob** [comment]
csv file of
```
grid_id, deepest_level, population, country, state, county
```
has gone to @prykon 

The url structure of `/nl/{grid_id}` has been suggested as a possibility to keep the keywords in the url to only those tagged on the end.

Due to the way that the magic links work, anything after the `{grid_id}` part can be ignored so urls like

`/nl/{grid_id}/pray-for-miami` will work exactly the same as `nl/{grid_id}`
