### ISSUE TITLE
User: registration

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#134]
Could we collect any prayer logs that the user may have already made, by finding any reports that have the same hash as the user who just registered.

In that way they wouldn't be starting from scratch if they registered on the same device and place that they prayed before?

After first user login

TODO:

- [x] delete some users from test
- [x] log some prayers as anon user
- [x] on user Registration: find any prayers with their current cache key, and change them to be attached to this new user

**Comment by ahillbilly** [comment]
I like this idea.  Grab anything stored in the cookie and include it in their registration setup.
