### ISSUE TITLE
Zero Population

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#15]
There are several states which have 0 population.

What do we want to do with these?

We could either skip them/not include them/have different prayers for them.

Either way some of the data needs to be massaged for these areas as in the database they have > 0% values for some things even though the population is 0.

**Comment by ChrisChasm** [comment]
Invested time into this. 

There are 12+ islands without population

Here is a nomination for a new query for 4910. This would include the counties of England 179. Remove 41 islands with low or no population. 

https://github.com/Pray4Movement/prayer-global-porch/wiki/Suggested-Query-for-4910

**Comment by ChrisChasm** [comment]
Fixed all zero populations. 
Updated location_grid_facts table, dt_location_grid, location_grid_4770

0988fff71396936e33ba96456815683671654e5d
