### ISSUE TITLE
Bug: when Northside finished their lap it set the start date to Jan 1, 1970

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#153]

**Comment by squigglybob** [comment]
On the map page of the lap, it's correct, so must be a bug on that page that's showing the date wrong.

![image](https://user-images.githubusercontent.com/9816214/214328604-56fa2bfb-2029-4993-9aa7-ff910bacfc29.png)

**Comment by squigglybob** [comment]
Looks like I need to update the locations per hour, to only count until the lap was finished as well, as that stat  of locations per hour/day is going to keep going down, the longer it's been since the lap finished

**Comment by ChrisChasm** [comment]
I fixed this by changing the links to the map as the completed page. 
At some point , we should fix the completed page.
