### ISSUE TITLE
Fix least reached image

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#20]
When no image is available from Joshua project for a least reached person, a warning image is displayed.

<img width="978" alt="Screenshot 2022-11-09 at 7 14 19 AM" src="https://user-images.githubusercontent.com/7318348/200853125-ba4cdcee-2f90-4aed-9490-c05d3c1d0475.png">

Replace this warning graphic with a mystery man image. Maybe one that is red to reflect the "least reached" category.

**Comment by squigglybob** [comment]
completed and accidentally pushed straight to master
