### ISSUE TITLE
Add confetti/fireworks animation to transition screen

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#26]
Currently there is a fireworks graphic that loads in between location screens, and after saying done before you go to the impact map. 

Task
1. Add a full page confetti animation to the transition screen between locations and between Done and the impact map.

https://www.loom.com/share/7e3cb593ada647089f8ade482569ff0e

https://www.jqueryscript.net/demo/Confetti-Animation-jQuery-Canvas-Confetti-js/

**Comment by squigglybob** [comment]
How about something like this?

https://www.loom.com/share/fc9aab76a5874a2889920f4ac5757991
