### ISSUE TITLE
Gap above the navigation 

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#32]
There is a gap at the top of the page above the navigation so that you can see scrolling content above your navigation.

push margin to top and add padding to reset position

**Comment by squigglybob** [comment]
hey @ChrisChasm 

Just checked it out on the website on iPhone 13, 14 and 14 Max Pro.

Can't see the issue there, so I'm wondering if it's an app thing?

could you confirm if it has the gap in the safari browser as well?

https://www.loom.com/share/552f772b25544450942411e8ae49678f

**Comment by ChrisChasm** [comment]
Okay, we can circle back to this. It's minor.
