### ISSUE TITLE
Profile login page broken

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#355]
window.getAuthUser function is not available on the profile screen

![image](https://github.com/Pray4Movement/prayer-global-porch/assets/9816214/5f68cac3-cd67-4ce7-bf8d-0f6457ebc016)

**Comment by corsacca** [comment]
Fixed with: https://github.com/DiscipleTools/disciple-tools-theme/commit/b1bc0cfd5299ae3ac96f19844aa2d2ffebe45221
