### ISSUE TITLE
maps: foot_block and legend taking up too much space on small screen

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#38]
on my wifes phone it looks something like this
![image](https://user-images.githubusercontent.com/9816214/201870533-cdcb223f-b99d-4b11-8d5d-9e062695894e.png)

something like 368x580 on a responsive viewport.

maybe we should reduce the font size and image size on small screens to reduce the vertical space taken up, or take it to another level and reorganise the positions of the foot_block and really squish it down to half it's size

what do you reckon @ChrisChasm

**Comment by ChrisChasm** [comment]
Agreed. This seems like an issue of some better mobile css sizing.

**Comment by squigglybob** [comment]
After some changing of
* padding
* icon size
* Places remaining --> remaining in the legend

screen res 350x634
![image](https://user-images.githubusercontent.com/9816214/202226223-96987dc1-05a5-4b62-8b8c-67ad4cbdaef0.png)
