### ISSUE TITLE
More accurate Time prayed

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#45]
### Discussed in https://github.com/Pray4Movement/prayer-global-porch/discussions/44

<div type='discussions-op-text'>

<sup>Originally posted by **squigglybob** November 16, 2022</sup>
At the moment this is just a best guess, as it is based on the user's chosen amount of time that they want to pray for.

E.g. a user is using the default 1min timer and prays for 20 places, they will be recorded as having prayed for 20 mins, even if they actually spent 5 mins praying for each place.

Should/Could we instead, track the time between them entering into a prayer experience for a place, and clicking next/done?

This would give a more accurate picture of time actually spent praying, but would also be an upper limit of time prayed, rather than the current lower limit of time prayed.

What do you think @ChrisChasm ?</div>

**Comment by squigglybob** [comment]
- [ ] send back record number when timer stops
- [ ] timer keeps going after hitting end of prayer time period
- [ ] create endpoint to add another minute to current prayer record
- [ ] at each next minute of time hit the endpoint to add time.
- [ ] stop the timer when Done/next is pressed
