### ISSUE TITLE
action handles should stay in place when scrolling

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#47]
https://www.loom.com/share/f2d0937b16354cb394adf3a99eac1406

The close handles in the flyovers should stay in place when scrolling the flyover content c.f. the footer in the maps on mobile or the location details when you click on a location on the map.

This would make it more intuitive how to close the flyover after you have scrolled

now that scrolling is fixed in #43 this issue is more noticeable

**Comment by ChrisChasm** [comment]
Totally agree.
