### ISSUE TITLE
Mobile View - Group Challenge List

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#50]
The current mobile view for the group challenge list uses datatables.js, which adds a nice search-ability and ordering. But the mobile view collapses and makes it awkward to click to visit the group page.

Make a nicer single click list view for the mobile view.

<img width="476" alt="Screenshot 2022-11-16 at 10 18 24 AM" src="https://user-images.githubusercontent.com/7318348/202249063-6dd0bf37-ea34-4705-9a19-f8b58a9a1ac7.png">

**Comment by squigglybob** [comment]
What about just expanded rows as default ?

https://www.loom.com/share/d42ea44ff32a42e1ac98e02f478ea3ee
