### ISSUE TITLE
pray for specific states

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#60]
Add a button on the location_details / stats page to allow users to pray for a specific place if they click on the map.

| Location Details Panel | Possible locations |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/9816214/203560393-f736f132-231c-4994-9154-29b937ed4fa3.png) | Could go on the sticky top bar or underneath the place name |

```mermaid
flowchart TD
pre1{{clicks on map}} --> pre2(opens location_details side bar for grid_id=123456789)
pre2 --> A
  A{{clicks on 'pray for this place'}} --> B(goes to /prayer_app/lap_type/hash?grid_id=123456789)
B --> C{{clicks done}}
C--> D(goes back to the map they came from)
B --> E{{clicks next}}
E --> F(goes to next random prayer)
F --> E
F --> C
```

**Comment by ChrisChasm** [comment]
I favor opening a modal from the map to a prayer experience and then letting them collapse back to the map and select another location.

I think keeping the map as the interactive experience is the fun factor. Actually, if we can have the prayer tool finish and we could trigger the map polygon to fill in as the celebration. That would be cool. 

I think the pray for focus countries is different vector to the system, and experience. That needs more discussion.

**Comment by squigglybob** [comment]
Agreed, the country focus is totally seperate to this ticket.

So something more like this?

```mermaid
flowchart TD
A{{user clicks polygon}} --> B(opens location details panel)
B --> C{{user clicks 'pray for this place'}}
C --> D(opens up modal containing the usual prayer experience but with pause/finished buttons that facilitate going back to the map)
D --> E{{clicks on done when finished praying}}
E --> F(Modal closes and drops the user back to the map)
F --> G([map is zoomed to surrounding area of prayed for place and shows celebration and map changing colour])
```

**Comment by squigglybob** [comment]
Paused prayer nav bar
![image](https://user-images.githubusercontent.com/9816214/203566432-950114e4-5641-46a3-9b2c-f920886fc722.png)

Done prayer nav bar
![image](https://user-images.githubusercontent.com/9816214/203566565-36501e37-959b-438f-bc11-9b1edbd0fae4.png)

**Comment by ChrisChasm** [comment]
I think it could be built against the global lap as a unique action with a variable.

```https://prayer.global/prayer_app/global/#######/country?grid_id=12345679```

1. This would require adding another `action`  to the global lap that reads the GET var
2. The action would skip the shuffle query and build directly from the `public static function build_location_stack_v2( $grid_id )`
3. If this was loaded inside a modal, it would be tempting to explore loading it as an iframe inside the modal so that you don't have to load the lap.js into the modal page. The lap.js file right now is written to initialize on load which makes it difficult to load ahead of time.

**Comment by squigglybob** [comment]
Here is how the experience would look/feel like if we used an iframe in a modal.

This one is just using the current prayer experience in a modal

https://www.loom.com/share/3ba45362eb0f4b9dbec341ed723cf9a1

**Comment by squigglybob** [comment]
adding eventlisteners to the buttons in the iframe to close the modal from the map page, turns out to be very simple too

**Comment by ChrisChasm** [comment]
Responding to the loom video.

"You don't have to add a layer. You can edit the geojson data source and it will update the current map layer with the right color. Look at the -display map. It has a 1 minute refresh timer that his updating the data-source without reloading the polygons."
