### ISSUE TITLE
how we could remove the legend

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#63]
### Discussed in https://github.com/Pray4Movement/prayer-global-porch/discussions/39

<div type='discussions-op-text'>

<sup>Originally posted by **squigglybob** November 15, 2022</sup>
So I've been thinking about how we could remove the need for the legend...
In my mind everything in the bottom section of the map *is* the legend.

Currently
![image](https://user-images.githubusercontent.com/9816214/201876754-8519b65b-aaba-47ae-ad5d-4ee0c20a9abe.png)

So we could emphasize the colours of the green and red in the foot block by reversing the colours of the numbers with the background like so...
![image](https://user-images.githubusercontent.com/9816214/201872361-239d7116-90f3-4feb-9be7-ce13407e9c6c.png)

would that make it more obvious that these are the colours represented on the map?
Or should we also make it more legendy like the legend I added.

Maybe something like this?
![image](https://user-images.githubusercontent.com/9816214/201876481-b3005d92-2efe-4cd2-9726-574679afdb83.png)

@ChrisChasm @corsacca @himayrunner @ahillbilly @prykon 
</div>

**Comment by ChrisChasm** [comment]
I like this best because it keeps the bottom info section from taking up too much space on the screen. On smaller screens this makes a big difference. Visually it should support the map, not compete as primary.

![](https://user-images.githubusercontent.com/9816214/201872361-239d7116-90f3-4feb-9be7-ce13407e9c6c.png)

**Comment by squigglybob** [comment]
when on a heatmap map, the current legend would come back into play to describe the new scale of colours
