### ISSUE TITLE
More accurate prayer timer needs to pause when the tab is not being interacted with

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#69]
I forgot to add a pause to the timer when the tab is not active.
So an ignored prayer tab will continue to rack up extra minutes of prayer

**Comment by ChrisChasm** [comment]
The behavior I have noticed is that most browsers and mobile browsers pause JavaScript while you are not focused on the tab. I know this is a fact for iPhone safari and Mac chrome.

But maybe other browsers and other operating systems do not do this

**Comment by squigglybob** [comment]
I had noticed that with the current prayer timer it paused, and had assumed that there was some code checking to do this. I'll double check whether this is or isn't an isuse

**Comment by squigglybob** [comment]
@ChrisChasm Yes your right. The tick gets paused in the same way as the time variable gets paused.
I must have had a split screen going when I saw this.

On my desktop if the browser is covered or the tab is changed it pauses.

If I switch to another window but can still see the prayer page, then the js keeps running which must have been what happened
