### ISSUE TITLE
404 interfering with route to take you to /completed

### ISSUE THREAD

**Issue by squigglybob** [Pray4Movement/prayer-global-porch#71]
In `magic-global.php` there is some logic to say that if the hash in the url doesn't match the current lap then redirect to the `.../completed` url.

The new 404 page is overriding that, and taking you straight to the 404 page if you tamper with the hash.

@ChrisChasm what should the behaviour be here?

**Comment by ChrisChasm** [comment]
A false hash should go to the 404 page. Only a completed lap should redirect to the completed page.

**Comment by squigglybob** [comment]
@ChrisChasm I can't remember what we decided on this.

I think I was going to look at maybe registering the /completed pages somehow. I'll message you if I get stuck with that
