### ISSUE TITLE
USA polygon does not have red for the state

### ISSUE THREAD

**Issue by ChrisChasm** [Pray4Movement/prayer-global-porch#74]
On the prayer page when you have a US state, the state does not turn red.

This could be an issue with the polygon format itself.

**Comment by squigglybob** [comment]
I think you are right on this one. I have had some states not turn red, and others turn red.

With the ability to pray for specific states coming up, this becomes easier to check

**Comment by squigglybob** [comment]
Just been looking at the code. I wonder if it's something to do with the zoom opacity

```js
            map.addLayer({
              'id': 'parent_collection_fill',
              'type': 'fill',
              'source': 'parent_collection',
              'filter': [ '==', ['get', 'grid_id'], grid_row.grid_id ],
              'paint': {
                'fill-color': 'red',
                'fill-opacity': 0.75
              }
            });
            map.setPaintProperty('parent_collection_fill', 'fill-opacity', [
              'interpolate',
              ['exponential', 0.5],
              ['zoom'],
              12,
              0.75,
              17,
              .05
            ]);
```

At zoom 17 the opacity is almost 0.
When I haven't seen the colour, the zoom has actually got more zoomed out to take in all of the USA, which could mean that the opacity is almost off, hence the no red zone...

**Comment by squigglybob** [comment]
nope, should have checked that before suggesting that one 😆 if you click on west virginia for example, there is no red at all.

This could suggest instead that the filter above when adding the layer isn't matching the grid_id correctly

**Comment by squigglybob** [comment]
OK, here's the difference that I can tell by looking at the data in the geojson responses.

Here's Alabama, which doesn't pick up the state for zooming or colouring
![image](https://user-images.githubusercontent.com/9816214/206196793-7124fc15-63aa-412b-bddd-054dcb005c94.png)

As you can see, the grid_id property in the `properties` array is an integer

Whereas for Alberta in Canada which works, the `grid_id` is a string.
![image](https://user-images.githubusercontent.com/9816214/206197362-f8005aea-c039-4695-ba1e-61589fed141a.png)
